spring:
  application:
    name: flagright-backend
  
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
    
server:
  port: 8080

logging:
  level:
    com.flagright: INFO
    org.neo4j: WARN
    org.springframework.data.neo4j: INFO 